/* methods_help.h
 * Heihaier <admin@heihaier.org>
 * http://www.heihaier.org
 */

#ifndef __METHODS_HELP_H__
#define __METHODS_HELP_H__

#define	HELP_INIT	"init(None)\n\nIf you want to use the pyfetion, you must invoke this function at first."
#define HELP_TERMINATE	"terminate(None)\n\nShutdown the pyfetion, when pyfetion isn't used any more."
#define HELP_CLOSE_NETWORK	"close_network(None)\n\nShutdown the connect to fetion's servers."
#define HELP_S_LOGIN	"s_login(uid, password)\n\nLogin fetion."
#define HELP_SET_LOGIN_STATUS	"set_login_status(login_status)\n\nSet the user login status."
#define HELP_LOGIN	"login(uid, password, callback_func, args)\n\nLogin fetion."
#define HELP_LOGINOUT	"loginout(None)\n\nLoginout fetion."
#define HELP_SET_SYSTEM_MSG_CB	"set_system_msg_cb(callback_func, args)\n\nSet the system message callback function."
#define HELP_GET_MSG	"get_msg(uid)\n\nGet the uid's message."
#define HELP_S_SEND_SMS	"s_send_sms(who, message)\n\nSimple send sms function."
#define HELP_S_SEND_SMS_BY_MOBILE_NO	"s_send_sms_by_mobile_no(mobile_no, message)\n\nSimple send sms function."
#define HELP_S_SEND_SMS_TO_SELF	"s_send_sms_to_self(message)\n\nSend a short message to user self."
#define HELP_SEND_SMS	"send_sms(who, message)\n\nSend sms."
#define HELP_SEND_SMS_TO_SELF	"send_sms_to_self(message)\n\nSend sms to self."
#define HELP_SEND_SMS_BY_MOBILE_NO	"send_sms_by_mobile_no(mobile_no, message)\n\nSend sms by mobile number."
#define HELP_SET_LONGSMS	"set_longsms(bl)\n\nSet the send sms mode, it maybe longsms or sms normally."
#define HELP_S_BEGIN_DIALOG	"s_begin_dialog(who)\n\nBegin the dialog function."
#define HELP_S_DIALOG_SEND	"s_dialog_send(who, message)\n\nSend a message to somebody in a dialog."
#define HELP_S_END_DIALOG	"s_end_dialog(who)\n\nEnd a dialog with somebody."
#define HELP_BEGIN_DIALOG	"begin_dialog(who)\n\nBegin the dialog function."
#define HELP_DIALOG_SEND	"dialog_send(who, message)\n\nSend a message to somebody in a dialog."
#define HELP_END_DIALOG	"end_dialog(who)\n\nEnd a dialog with somebody."
#define HELP_GET_USR_UID	"get_usr_uid(None)\n\nGet a current user id uid."
#define HELP_GET_USR_PASSWD	"get_usr_passwd(None)\n\nGet a current user is password."
#define HELP_GET_USR_SHOW_NAME	"get_usr_show_name(None)\n\nGet a current user is name."
#define HELP_GET_USR_URI	"get_usr_uri(None)\n\nGet a current user is uri."
#define HELP_GET_USR_MOBILENUM	"get_usr_mobilenum(None)\n\nGet a current user is mobile number."
#define HELP_GET_USR_SCORE	"get_usr_score(None)\n\nGet the user is score."
#define HELP_SET_USER_STATE	"set_user_state(state=['online'|'busy'|'away'|'dinner'], desc)\n\nSet the user state."
#define HELP_GET_USER_STATE	"get_user_state(None)\n\nGet the user state."
#define HELP_SET_USER_IMPRESA	"set_user_impresa(impresa)\n\nSet the user impresa."
#define HELP_SET_USER_NICKNAME	"set_user_nickname(nickname)\n\nSet the user nickname."
#define HELP_GET_USER_REFUSE_SMS_DAY	"get_user_refuse_sms_day(None)\n\nGet the user how long day to receive the sms message."
#define HELP_SET_USER_REFUSE_SMS_DAY	"set_user_refuse_sms_day(days)\n\nSet the user how long to receive the sms message."
#define HELP_GET_EXPIRETIME	"get_expirestime(None)\n\nGet the expires time of the fetion."
#define HELP_DATA_GET_PERSONALINFO	"data_get_PersonalInfo(None)\n\nGet a current user id personal information."
#define HELP_GET_GROUP	"get_group(None)\n\nGet the fetion's group information."
#define HELP_GET_ACCOUNT	"get_account(None)\n\nGet the fetion's all accounts information."
#define HELP_GET_BLACKLIST	"get_blacklist(None)\n\nGet the fetion's all black's accounts information."
#define HELP_GET_QUN	"get_qun(None)\n\nGet the fetion's qun information."
#define HELP_GET_ACCOUNT_BY_ID	"get_account_by_id(id)\n\nGet a account which uid's the gvied id"
#define HELP_GET_QUN_BY_ID	"get_qun_by_id(id)\n\nGet qun which uid's gived id."
#define HELP_IS_PC_USER_BY_ID	"is_pc_user_by_id(id)\n\nJudge this id is PC user or not."
#define HELP_IS_PC_USER_BY_ACCOUNT	"is_pc_user_by_account(account)\n\nJudge this account is PC user or not."
#define HELP_IS_AUTHED_BY_ID	"is_authed_by_id(id)\n\nJudge this id is auth to you add it."
#define HELP_IS_AUTHED_BY_ACCOUNT	"is_authed_by_account(account)\n\nJudge this account is auth to you add it."
#define HELP_IS_INBLACKLIST_BY_ID	"is_InBlacklist_by_id(id)\n\nJudge this account is in the blacklist."
#define HELP_IS_INBLACKLIST_BY_ACCOUNT	"is_InBlacklist_by_account(account)\n\nJudge this account is in the blacklist."
#define HELP_MOVE_GROUP_BUDDY_BY_ID	"move_group_buddy_by_id(uid, group_id)\n\nModify the group which account was belonged."
#define HELP_MOVE_GROUP_BUDDY	"move_group_buddy(account, group_id)\n\nModify the group which account was belonged."
#define HELP_IS_ON_LINE_BY_ID	"is_on_line_by_id(id)\n\nJudge this id is online or not."
#define HELP_IS_ON_LINE_BY_ACCOUNT	"is_on_line_by_account(account)\n\nJudge this account is online or not."
#define HELP_GET_ON_LINE_STATUS_BY_ID	"get_online_status_by_id(id)\n\nReturn fetion uid's online status."
#define HELP_GET_ON_LINE_STATUS_BY_ACCOUNT	"get_online_status_by_account(account)\n\nReturn fetion account's online status."
#define HELP_GET_REFUSE_SMS_DAY	"get_refuse_sms_day(account)\n\nReturn fetion account's refuse_sms_day."
#define HELP_UPDATA_ACCOUNT_INFO_BY_ID	"updata_account_info_by_id(id)\n\nUpdate the account info which uid's the gived id."
#define HELP_UPDATA_ACCOUNT_INFO_ALL	"updata_account_info_all(None)\n\nUpdate all the account info."
#define HELP_GET_ACCOUNT_SHOW_NAME	"get_account_show_name(account, needImpresa)\n\nGet the show name of the account."
#define HELP_GET_QUN_SHOW_NAME	"get_qun_show_name(qun)\n\nGet the show name of the qun."
#define HELP_GET_ACCOUNT_GROUP_ID	"get_account_group_id(account)\n\nGet the group id of the account."
#define HELP_S_RENAME_BUDDYLIST	"s_rename_buddylist(id, name)\n\nRename the group."
#define HELP_S_DELETE_BUDDYLIST	"s_delete_buddylist(id)\n\nDelete a group."
#define HELP_RENAME_BUDDYLIST	"rename_buddylist(id, name)\n\nRename the group."
#define HELP_ADD_BUDDYLIST	"add_buddylist(name)\n\nAdd a buddylist."
#define HELP_ADD_BUDDY_BY_UID	"add_buddy_by_uid(uid, local_name, groupid, desc)\n\nAdd a account by fetion id."
#define HELP_ADD_BUDDY_BY_MOBILE	"add_buddy_by_mobile(mobile, local_name, groupid, desc)\n\nAdd a account by mobile number."
#define HELP_HANDLECONTACTREQUEST	"handleContactRequest(uri, isPassed, group, local_name)\n\nHandle a request of addaccount."
#define HELP_DELETE_BUDDYLIST	"delete_buddylist(id)\n\nDelete a group."
#define HELP_S_SET_BUDDYINFO	"s_set_buddyinfo(uid, localname)\n\nSet the local name of the account."
#define HELP_SET_BUDDYINFO	"set_buddyinfo(uid, localname)\n\nSet the local name of the account."
#define HELP_DELETE_BUDDY_BY_ID	"delete_buddy_by_id(uid)\n\nDelete the account."
#define HELP_DELETE_BUDDY_BY_ACCOUNT	"delete_buddy_by_account(account)\n\nDelete the account."
#define HELP_ADDTO_BLACKLIST_BY_ID	"addto_blacklist_by_id(uid)\n\nAdd the user to blacklist."
#define HELP_ADDTO_BLACKLIST_BY_ACCOUNT	"addto_blacklist_by_account(account)\n\nAdd the user to blacklist."
#define HELP_ADDTO_BLACKLIST_BY_URI	"addto_blacklist_by_uri(uri)\n\nAdd the uri user to blacklist."
#define HELP_REMOVEFROM_BLACKLIST_BY_ID	"removefrom_blacklist_by_id(uid)\n\nRemove the user from blacklist."
#define HELP_REMOVEFROM_BLACKLIST_BY_ACCOUNT	"removefrom_blacklist_by_account(account)\n\nRemove the user from blacklist."
#define HELP_REMOVEFROM_BLACKLIST_BY_URI	"removefrom_blacklist_by_uri(uri)\n\nRemove the uri user from blacklist."
#define HELP_SEND_NUDGE	"send_nudge(who)\n\nSend a nudge."
#define HELP_SET_SERVE_ADDRESS	"set_serve_address(serve_address)\n\nSet the fetion proxy ip and port, the proxy format is ip:port (192.168.0.1:8080)."
#define HELP_SET_UNKNOW_SERVE_ADDRESS	"set_unkonw_serve_address(None)\n\nLet the fetion get the serve_address ip and port by it self."
#define HELP_GET_SERVE_ADDRESS	"get_serve_address(None)\n\nGet the current fetion id's proxy server ip, the ip format is ip:port (192.168.0.1:8080)."
#define HELP_SET_PROXY	"set_proxy(proxy)\n\nSet the proxy when you use proxy to connect the network."
#define HELP_GET_PROXY	"get_proxy(None)\n\nGet the Get the proxy information."
#define HELP_TEST_NETWORK	"test_network(proxy)\n\nGet the fetion network is working of proxy."
#define HELP_SIMPLE_PASER_MSG	"simple_paser_msg(msg)\n\nSimple paser the msg filter the <Font></Font> tags."

#endif /* __METHODS_HELP_H__ */
